EQUIPO = red.datos.secuencial.EquipoSecuencialDao
CONEXION = red.datos.secuencial.ConexionSecuencialDao
UBICACION = red.datos.secuencial.UbicacionSecuencialDao
TIPOEQUIPO = red.datos.secuencial.TipoEquipoSecuencialDao
TIPOCABLE = red.datos.secuencial.TipoCableSecuencialDao
TIPOPUERTO = red.datos.secuencial.TipoPuertoSecuencialDao


#EQUIPO = red.datos.sql.EquipoPostgreSqlDao
#CONEXION = red.datos.sql.ConexionPostgreSqlDao
#UBICACION = red.datos.sql.UbicacionSecuencialDao
#TIPOEQUIPO = red.datos.sql.TipoEquipoPostgreSqlDao
#TIPOCABLE = red.datos.sql.TipoCablePostgreSqlDao
#TIPOPUERTO = red.datos.sql.TipoPuertoPostgreSqlDao